version: "3.7"
services:
  twello-api:
    image: twello-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    container_name: twello-api
    depends_on:
      - twello-db
    links:
      - twello-db
    volumes:
      - .:/home/node/twello-api
      - /home/node/twello-api/node_modules
      - ./files:/home/node/twello-api/files
    ports:
      - "4005:4005"

  twello-db:
    image: postgres:11.12
    container_name: twello-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: twello-db
    volumes:
      - twdodbdata:/var/lib/twello-db/data
    ports:
      - "5430:5432"

volumes:
  twdodbdata:
    driver: local
